### ISSUE TITLE
Space Giraffe (ugly peanut with a dingus) does not disappear.

### ISSUE THREAD

**Issue by vijer** [SpaceGameDev568/RemoveAllAnnoyances#3]
The title says it all.

**Comment by SpaceGameDev568** [comment]
Hi vijer!
With the information you provided I was unable to replicate this issue on my own. In order to properly debug this, I will need the following information from you:

**Satisfactory Version** - CL # in the top left corner

**RAA Version** - You can find this in the "Mods" section of the main menu when you choose RAA from the list

**RAA Options** -  What Annoyances have you selected that produce this behavior (also in the previously mentioned section)?

**Please note that you must give sufficient time for some Annoyances to disappear, which can take up to 30 seconds.**

Best regards,
SpaceGameDev

**Comment by vijer** [comment]
The time has been days, not 30 seconds. /shrug




On 1/7/2024 9:05:26 PM, Jesse Hodgson ***@***.***> wrote:
Hi vijer!
With the information you provided I was unable to replicate this issue on my own. In order to properly debug this, I will need the following information from you:
Satisfactory Version - CL # in the top left corner
RAA Version - You can find this in the "Mods" section of the main menu when you choose RAA from the list
RAA Options - What Annoyances have you selected that produce this behavior (also in the previously mentioned section)?
Please note that you must give sufficient time for some Annoyances to disappear, which can take up to 30 seconds.
Best regards,
SpaceGameDev

**Comment by SpaceGameDev568** [comment]
OK, that's helpful, but I still need that other information to continue debugging. Thanks in advance.

**Comment by vijer** [comment]
Which information? I thought the images had the CL number and the Mod version number.

CL#273254
Mod Loader v 3.6.1+349
Space Game Dev 1.2.2

Remove Alien Artifacts (checked)
Remove Manta Rays (checked)
Remove Destructible Rocks (checked)
Remove Space Giraffe (checked) 

I haven't confirmed the Alien Artifacts
Manta Rays seem to be gone
Destructible Rocks are not gone
Space Giraffe sometimes will display in the distance and disappear when you approach. Sometimes though, they do not disappear. 

On 1/8/2024 4:35:52 AM, Jesse Hodgson ***@***.***> wrote:
OK, that's helpful, but I still need that other information to continue debugging. Thanks in advance.

**Comment by SpaceGameDev568** [comment]
Hey again!

I think I've fixed the issue in the latest update to RAA, so please let me know if this works. 

https://ficsit.app/mod/FGnDVTV2ygmANY/version/79nV1VzoQPc4u4

**Comment by vijer** [comment]
The Space Giraffes appear to be gone now. 
The Destructible Rock are still displayed. 


On 1/9/2024 2:23:42 AM, Jesse Hodgson ***@***.***> wrote:
Hey again!
I think I've fixed the issue in the latest update to RAA, so please let me know if this works.
https://ficsit.app/mod/FGnDVTV2ygmANY/version/79nV1VzoQPc4u4 [https://ficsit.app/mod/FGnDVTV2ygmANY/version/79nV1VzoQPc4u4]

**Comment by SpaceGameDev568** [comment]
Hmm, this is some really odd behavior. I'm sorry to have to ask you for more information, but it looks like I may need to get your full game debug information. Please load  a save once in game with the mod installed and then generate debug info in the Mod Manager and send the zip file here.  You may need to do so on [GitHub](https://github.com/SpaceGameDev568/RemoveAllAnnoyances/issues/3) instead of via email so that I can view the attachments. Thank you for your cooperation. <br/><br/> ![](https://docs.ficsit.app/satisfactory-modding/latest/_images/FAQ/SmmGenerateDebugInfo.png)

**Comment by vijer** [comment]
Here is the debug file. 
[Uploading SMMDebug_2024-1-9_16-49-20.zip…]()

**Comment by vijer** [comment]
Here is the debug file. I sent it in Github too.
On 1/9/2024 8:55:22 PM, Jesse Hodgson ***@***.***> wrote:
Hmm, this is some really odd behavior. I'm sorry to have to ask you for more information, but it looks like I may need to get your full game debug information. Please load a save once in game with the mod installed and then generate debug info in the Mod Manager and send the zip file here. You may need to do so on GitHub [https://github.com/SpaceGameDev568/RemoveAllAnnoyances/issues/3] instead of via email so that I can view the attachments. Thank you for your cooperation.

[https://camo.githubusercontent.com/e01ffbc4c140e8051d18aa7d797366d3f835901f13633f69ae69bd42bb1b658c/68747470733a2f2f646f63732e6669637369742e6170702f7361746973666163746f72792d6d6f6464696e672f6c61746573742f5f696d616765732f4641512f536d6d47656e65726174654465627567496e666f2e706e67]

**Comment by SpaceGameDev568** [comment]
I think there must have been some error when you uploaded it, as the message on github.com you sent with the zip file is just a hyperlink that leads back to this issue page. The one attached in you email reply doesn't work either as attachments in email replies are not sent to GitHub. Please make sure that you are using this button to select the file and wait for it to finish uploading just in case.
![image](https://github.com/SpaceGameDev568/RemoveAllAnnoyances/assets/95051062/25833762-e564-4fb7-986c-403300b5800a)

**Comment by vijer** [comment]
[SMMDebug_2024-1-9_16-49-20.zip](https://github.com/SpaceGameDev568/RemoveAllAnnoyances/files/13882257/SMMDebug_2024-1-9_16-49-20.zip)

**Comment by SpaceGameDev568** [comment]
After reviewing the logs you provided, I have not been able to find any problem with the mod's functionality. I have however, found that there may be a mod incompatibility issue. You have installed [Vanish SpaceGiraffeTickPenguin](https://ficsit.app/mod/VanishGiraffer) and [Invisible Flying Manta](https://ficsit.app/mod/InvisibleManta) alongside RAA. This may be partly to blame for some of the issues you were encountering. If there is anything else that is not behaving as expected it is most likely due to a configuration issue on your end, and I would encourage you to look into it on your own. For now though, I will not be able to help you any further and will therefore be closing this issue.

Thank you for using my mods, and have a nice day.

Best regards,
SpaceGameDev

**Comment by vijer** [comment]
Hey Jesse,

Vanish SpaceGiraffeTickPenguin [https://ficsit.app/mod/VanishGiraffer] and Invisible Flying Manta [https://ficsit.app/mod/InvisibleManta] were installed, but both of them were paused. In any event, that part of your mod was fixed after your update. I did remove both of those mods and the Destructible Rocks still appear. That is the only open issue. I'm not sure how it could be a configuration issue as there aren't any other mods that try to hide/remove the rocks.  I guess I could start a new game with only your mod and see if I still have the issue.

Thanks for your time.

Vince

Anyway, you tried and can't reproduce my issue, and hiding the giraffes and mantas are more important than the rocks. So, partial functionality is better than none. 


On 1/10/2024 11:05:23 PM, Jesse Hodgson ***@***.***> wrote:
Closed #3 [https://github.com/SpaceGameDev568/RemoveAllAnnoyances/issues/3] as completed.

**Comment by vijer** [comment]
I started a new game with only RemoveAllAnnoyances, and the Destructible Rocks are still visible.

[SMMDebug_2024-1-10_20-48-36.zip](https://github.com/SpaceGameDev568/RemoveAllAnnoyances/files/13893937/SMMDebug_2024-1-10_20-48-36.zip)

**Comment by SpaceGameDev568** [comment]
Hi Vince,

To be completely honest with you, I'm not sure why this issue could be occurring. I have tested this mod extensively on my own and have found everything to be functioning as expected. Maybe you could try enabling other stuff to remove and see if those are working properly, and maybe there could be some commonality in that.

Also, maybe the mod itself became corrupted during the download. You could try deleting the `RemoveAllAnnoyances` folder from 
`D:/Games/SteamLibrary/steamapps/common/Satisfactory/FactoryGame/Mods` and redownloading it from SMM, if you haven't already.

And finally, I've published another update to RAA that doesn't specifically target this issue but may have an affect on it. https://ficsit.app/mod/RemoveAllAnnoyances/version/3wpUioQsRsRBKR

I'm not saying any of this will work, but it's all that I can think of.

Best regards,
Jesse

**Comment by vijer** [comment]
Yeah, uninstalling the mod didn't fix it. Maybe I'll uninstall the game and reinstall it. Anyway, removing the giraffes and rays is more important to me, and those both work.

Cheers
On 1/11/2024 9:49:50 AM, Jesse Hodgson ***@***.***> wrote:
Reopened #3 [https://github.com/SpaceGameDev568/RemoveAllAnnoyances/issues/3].

**Comment by SpaceGameDev568** [comment]
Yeah, I've got nothing for you then. I'm really sorry I couldn't make this feature work for you, but I hope you are at least somewhat satisfied with what I did get working. If you ever find the solution to this issue on your own please be sure to let me know. For now though, I will be closing the issue indefinitely as a fix seems unlikely.

Best regards,
Jesse
